### ISSUE TITLE
Add support for Promises

### ISSUE THREAD

**Issue by oksas** [honza/node-thumbnail#11]
Hi there, it would be awesome if this module supported Promises as well as traditional Node callbacks. This is actually something I would love to tackle myself and submit a PR for if that's okay with you!

**Comment by honza** [comment]
Yes, please! :heart:

**Comment by oksas** [comment]
Sweet, I will work on that this week and post a PR soon as I've got things sorted out. I'll let you know if I run into any issues! Thanks man!
