### ISSUE TITLE
No thumbnail produced

### ISSUE THREAD

**Issue by Ejyption** [honza/node-thumbnail#17]
I have installed and included the library,
all runs fine with source folders and destination folder.
As my nodejs server runs it prints out all the names of the images through the node-thumbnail library.
The callback prints 'All done!'
But no files are in the destination folder.

I am unsure of what the problem could be

**Comment by honza** [comment]
What version? Master or from the npm distribution?

**Comment by honza** [comment]
Can you post some sample code to help me debug this?

**Comment by ntpnhan** [comment]
I encounter the same problem, i install via "npm install node-thumbnail"

**Comment by honza** [comment]
@ntpnhan Can you post some sample code to help me debug this?

**Comment by shvhh** [comment]
var fs = require('fs');
var gm = require('gm');
var path  = require("path");
var express = require('express');
var multer  = require('multer');
var app = express();
var storage = multer.diskStorage(
{
	destination: function(request, files, callback)
	{
		callback(null,path.join(__dirname,'/uploads'));
	},
	
	filename:function(request, files, callback)
	{
		callback(null,Date.now()+files.originalname);
	}
	
});

var upload = multer({storage: storage});
var thumb = require('node-thumbnail').thumb;
app.use('/static', express.static(path.join(__dirname, 'uploads')))

app.post('/addimg',upload.any(), function (req, res) 
	{ 
	
	thumbnailc(req.files[0].filename);
	
	res.sendFile(__dirname + '/index.html'); 
	 });
	 
	 
	app.get('/' , function(req,res){
	res.sendFile(__dirname + '/index.html');
		
	});
	
	// https://github.com/honza/node-thumbnail/issues/17  post a issue on this, everything is fine 
	function thumbnailc(name)
	{	
		thumb({ 
	source:  'abc.jpg',
	destination:   path.join(__dirname,'uploads/thum'),
	concurrency: 1
	}, function(err) {
	console.log('All done!',err);
	});
	};
	
	
var server = app.listen(8081, function () 
{
   var host = server.address().address;
   var port = server.address().port;
   
   console.log("Example app listening at http://%s:%s", host, port)
});

**Comment by shvhh** [comment]
help me out

**Comment by shvhh** [comment]
no output

**Comment by honza** [comment]
@shvhh Does the destination file exist?

**Comment by honza** [comment]
I just published `0.8.1` to npm, would you mind trying that? It has better error messages.

**Comment by shvhh** [comment]
yes it is

**Comment by Hardik21** [comment]
I have same problem, How to solve it?

**Comment by honza** [comment]
@Hardik21 

You should inspect the value of the `err` argument in the callback to see if any errors occurred. For example:

```js
thumb(options, function(err, stdout, stderr) {
  if (err) {
    throw err;
  }

  console.log('All done!');
});
```

Also, please note that the `source` and `destination` configuration options should point to directories, not files.

Please let me know if you're still having issues. I'm happy to help.

**Comment by Hardik21** [comment]
Hi, 
For 'source': it is filepath with filename. Bcz without filename how to identify image for thumbnail?
For 'destination': I set only path without filename. 
Am i right?

And,

I set
`thumb(options, function(err, stdout, stderr) {
  if (err) {
    console.log(err);
  }

  console.log('All done!');
});`

Then it show in console: 'undefined'.

**Comment by honza** [comment]
Here is my directory structure:

    code.js
    dest/
    package.json
    src/
        cat.jpg

Here is `package.json`:

```json
{
  "name": "test",
  "dependencies": {
    "node-thumbnail": "^0.8.1"
  }
}
```

Here is `code.js`:


```js
var thumb = require('node-thumbnail').thumb;

thumb({
  source: 'src/cat.jpg',
  destination: 'dest',
  concurrency: 1,
  overwrite: true,
  width: 50, height: 50
}, function (err, stdout, stderr) {
  console.log('All done!');
});
```

The `src/` direcotory has a single image in it, called `cat.jpg`.

I install the dependencies with `npm install`.

Then, I run the code like this:

    $ node code.js


Here is the output:

    cat.jpg
    All done!
    all items have been processed


This is with:

* nodejs v6.10.2
* npm 3.10.10

**Comment by Hardik21** [comment]
I also get that output. But thumb image not generated in destination directory.

**Comment by honza** [comment]
Can you create a minimal project directory that reproduces this issue, tar it up, and send it to me?

**Comment by Hardik21** [comment]
Hi, I send mail to your email address: 'me@honza.ca'. I am not able to attach here. Plz check mail and help me to find out solution.

**Comment by Hardik21** [comment]
Hi, I upload demo code in Google Drive. Plz download from there and help me to solve. 

[Click Here for google drive](https://drive.google.com/file/d/0B9TUonxdPOBaYW5TUDFNcXNVNWs/view)

Thanks

**Comment by honza** [comment]
Unfortunately, your example works perfectly for me.

**Comment by honza** [comment]
What is your nodejs and npm version? What operating system are you using?

**Comment by Hardik21** [comment]
node: v6.7.0
npm: 4.5.0
OS: Windows 7 64bit

**Comment by Hardik21** [comment]
you have generate thumb image in './Media/ChatDocUpload_Thumb/'?

**Comment by honza** [comment]
I just released version `0.9.0` which removes the dependency on imagemagick. I think that's what is causing the issue on Windows. If you upgrade, you will get a version that's only using Javascript.

**Comment by Hardik21** [comment]
Yes. Version 0.9.0 is perfect for windows. Its working awesome. You save my one day. Thanks

**Comment by honza** [comment]
:sparkles:
