### ISSUE TITLE
Error: spawn convert ENOENT

### ISSUE THREAD

**Issue by caiopinheiro** [honza/node-thumbnail#18]
`{Error:` spawn convert ENOENT
    at exports._errnoException (util.js:1036:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn convert',
  path: 'convert',
  spawnargs: 
   [ '/path/to/image',
     '-set',
     'option:filter:blur',
     '0.8',
     '-filter',
     'Lagrange',
     '-strip',
     '-resize',
     '800',
     '-quality',
     '80',
     `'/path/to/thumb]` }

This is the error that appears when generating a thumbnail, can you help me?

Thanks.

**Comment by honza** [comment]
How did you trigger this issue? What version of node?

**Comment by caiopinheiro** [comment]
I used the node-thumbnail as described in the documentation. Below is the code. My version of the node is 6.6.0.

```
var thumb = require('node-thumbnail').thumb

	thumb({
		  source: myPath +'/'+file.filename, 
		  destination: myPath,
		  concurrency: 1, // The value was 4 but I changed it to 1
			suffix: '_thumb'
		}, function(err) {
			if(err){
				console.log(err);
			}
		  console.log('All done!');
		});
```

**Comment by honza** [comment]
Cannot reproduce. What are the values of `myPath` and `file`?

**Comment by caiopinheiro** [comment]
myPath is `/uploads/images` and the `file` is an object that comes in the request.

**Comment by honza** [comment]
This ENOENT error is caused by the absence of the ImageMagick command line tools. Please install the package, and try again. I'll see about adding a better error message.

**Comment by caiopinheiro** [comment]
It worked, thanks for the help!

**Comment by anthousecode** [comment]
> It worked, thanks for the help!

how you did it?

**Comment by nomi-shah** [comment]
same error plz help
