### ISSUE TITLE
Anyway to get the thumbnail file name ?

### ISSUE THREAD

**Issue by johnnytn** [honza/node-thumbnail#21]
Is there a way to get the thumbnail name after creating it? 
Is there a return param to get any data after everything is done?

I just don't wanna need to break create the name breaking the original file name D:

**Comment by honza** [comment]
What kind of API are you picturing? An array of filenames in the callback?

**Comment by johnnytn** [comment]
Just 1 file.
 And 1 more thing `jimp` doesn't support `gif` right? Was just wondering why there are ` '.gif',
  '.GIF'` extensions inside `thumbnail.js` 🤔

**Comment by honza** [comment]
OK, so now it'll die loudly when using unsupported extensions 0a63732c248337232a01f375273fd825b0c1b98d

I'm checking into the resulting filenames now.

**Comment by johnnytn** [comment]
Thanks for the fix @honza, but don't you think returning the `error` in the `callback` just like the  *Destination does not exist* better?

**Comment by johnnytn** [comment]
Thanks for the fix @honza appreciate it very much 😄
