### ISSUE TITLE
the most recent version gives error

### ISSUE THREAD

**Issue by levidrain** [honza/node-thumbnail#22]
The most recent version gives me this error:
"UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error
: Unsupported file format."

The previous version works.  I assume this is because the source folder also contains files that aren't images.

**Comment by honza** [comment]
Interesting. I guess we should make this configurable. I'll have a look.

**Comment by honza** [comment]
@levidrain I added an option to ignore unsupported files. Try it out in `0.11.0`.
