### ISSUE TITLE
Second time not working

### ISSUE THREAD

**Issue by soravmobi** [honza/node-thumbnail#30]
Hi i have started my server and the upload image, its create thumbnail, but when i am uploading image again then image uploading but thumbnail not createing, also not getting response, not going into thumb call back function.

**Comment by soravmobi** [comment]
finally i catch the issues, second time uploaded file name was same, if same file image already exist in directiory, then its not genertae image thumbnail, also didn`t get any response, its a bug in your module, please correct it.

**Comment by williamdes** [comment]
Same issue

**Comment by honza** [comment]
I just published `0.14.0` which includes @williamdes patch. Give it a go.

**Comment by williamdes** [comment]
@honza Perfect, no more bug, issue closed.
@soravmobi Close ?

**Comment by soravmobi** [comment]
Hi,

Thanks for your reply, honestly I didn`t the chance to check it, but for now you can close it :)
