### ISSUE TITLE
Can not create a thumbnail with the given api

### ISSUE THREAD

**Issue by LingboTang** [honza/node-thumbnail#7]
I just copy and paste the following code in myThumb.js:

```
var thumb = require('node-thumbnail').thumb;

// thumb(options, callback);

thumb({
  source: 'C:/<User>/Documents/GitHub/myNodeThumb/Balls.jpg', // could be a filename: dest/path/image.jpg
  destination: 'C:/<User>/Documents/GitHub',
  concurrency: 4
}, function(err) {
  console.log('All done!');
});
```

and my file structure was:
myNodeThumb
|--myThumb.js
|--Balls.jpg
|--node_modules

when I run `node myThumb.js`, I can't generate a thumbnail in the dest path.

**Comment by honza** [comment]
Do you get an error?

I don't have access to a windows machine to test this, unfortunately.

**Comment by LingboTang** [comment]
The function will return the file name: "Balls.jpg", but it will also display the error message: "All done!"

**Comment by LingboTang** [comment]
The problem is here: 

```
_.each(images, function(image) {

    options = {
      srcPath: settings.soucre + '/' + image,
      width: settings.width
    };

    queue.push({options: options}, function() {
      if (!settings.quiet) {
        console.log(image);
      }
    });

  });
```
When you push images to the queue, in {options: options}, srcPath will become undefined

**Comment by LingboTang** [comment]
I have imageMagick binary executable installed on windows 10.

**Comment by LingboTang** [comment]
@honza Actually it's windows path syntax problem. I fixed it by passing source: "C:\\<User>\\path\\to\\image"

**Comment by honza** [comment]
:+1:

**Comment by Ejyption** [comment]
I am on windows, running in my nodejs app, the server prints out all of the filenames that are images in source folder, has no errors and server prints out the callback 'All done!'. But no thumbnails are created

**Comment by Ejyption** [comment]
are there required libraries needed to use node-thumbnail ?
